In [17]:
## Image Plate Diffraction System ##

## Transformation Matrix ##

## Empa, Center for X-ray Analytics, D.Sapalidis, St. Gallen, Switzerland, 21.12.2023 ##

import numpy as np


# Construction of the Euler rotation matrix from lab coordination system to sample coordination system

def euler_rotation_matrix(omega, psi, phi):
    
    
    # Conversion degrees to radians
    
    omega_rad = np.radians(omega)
    psi_rad = np.radians(psi)
    phi_rad = np.radians(phi)

    
    a11 = - (np.sin(omega_rad) * np.sin(psi_rad) * np.sin(phi_rad)) - (np.cos(omega_rad) * np.cos(phi_rad))
    a12 = (np.cos(omega_rad) * np.sin(psi_rad) * np.sin(phi_rad)) - (np.sin(omega_rad) * np.cos(phi_rad))
    a13 = - (np.cos(psi_rad) * np.sin(phi_rad))

    a21 = (np.sin(omega_rad) * np.sin(psi_rad) * np.cos(phi_rad)) - (np.cos(omega_rad) * np.sin(phi_rad))
    a22 = - (np.cos(omega_rad) * np.sin(psi_rad) * np.cos(phi_rad)) - (np.sin(omega_rad) * np.sin(phi_rad))
    a23 = (np.cos(psi_rad) * np.cos(phi_rad))

    a31 = - (np.sin(omega_rad) * np.cos(psi_rad))
    a32 = (np.cos(omega_rad) * np.cos(psi_rad))
    a33 = np.sin(psi_rad)

    transformation_matrix = np.array([[a11, a12, a13],
                                     [a21, a22, a23],
                                     [a31, a32, a33]])

    return transformation_matrix


# Definition of the unit diffraction vector in laboratory coordinates

def unit_diffraction_vector(theta, gamma):
    
    
    # Conversion degrees to radians
    
    theta_rad = np.radians(theta)
    gamma_rad = np.radians(gamma)
    
    hx = - np.sin(theta_rad)
    hy = - (np.cos(theta_rad) * np.sin(gamma_rad))
    hz = - (np.cos(theta_rad) * np.cos(gamma_rad))
    
    diffraction_vector_matrix = np.array([[hx],
                                         [hy],
                                         [hz]])
    
    return diffraction_vector_matrix

    
# Definition of the unit diffraction vector in sample coordinates

def sample_diffraction_vector(transformation_matrix, diffraction_vector_matrix):
    
    sample_diffraction_vector_matrix = np.dot(transformation_matrix, diffraction_vector_matrix)
    
    return sample_diffraction_vector_matrix
   
    
    
# Input the angle values here

omega_angle = 30  # Angular rotation ω in degrees
psi_angle = 45    # Angular rotation ψ in degrees
phi_angle = 60    # Angular rotation φ in degrees
theta_angle = 40  # The diffraction angle θ in degrees 
gamma_angle = 20  # Azimuthal angle γ in degrees

transformation_matrix = euler_rotation_matrix(omega_angle, psi_angle, phi_angle)
diffraction_vector_matrix = unit_diffraction_vector(theta_angle, gamma_angle)
sample_diffraction_vector_matrix = sample_diffraction_vector(transformation_matrix, diffraction_vector_matrix)

print("Transformation Matrix:")
print(transformation_matrix)
print("Unit Diffraction Vector Matrix")
print(diffraction_vector_matrix)
print("Unit Diffraction Vector Matrix in Samples Coordinates")
print(sample_diffraction_vector_matrix)

Transformation Matrix:
[[-0.73919892  0.28033009 -0.61237244]
 [-0.5732233  -0.73919892  0.35355339]
 [-0.35355339  0.61237244  0.70710678]]
Unit Diffraction Vector Matrix
[[-0.64278761]
 [-0.26200263]
 [-0.71984631]]
Unit Diffraction Vector Matrix in Samples Coordinates
[[ 0.84251473]
 [ 0.3076288 ]
 [-0.44219166]]
